# 应用服务 WEB 访问端口
server:
  port: 9101
spring:
  application:
    name: sharding-jdbc-demo
  shardingsphere:
    mode:
      type: Memory #内存模式，无需持久化
    rules:
      sharding:
        tables:
          user:
            actualDataNodes: user-0.user_$->{0..1}
            tableStrategy:
              standard:
                shardingColumn: user_id
                shardingAlgorithmName: table-inline
        shardingAlgorithms:
          table-inline:
            type: INLINE
            props:
              algorithm-expression: user_$->{user_id%2}
      readwrite-splitting:
        data-sources:
          user:
            type: static
            props:
              write-data-source-name: user-0
              read-data-source-names: user-1
        load-balancers:
          ROUND_ROBIN:
            type: ROUND_ROBIN
    datasource:
      names: user-0,user-1
      user-0:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://localhost:3308/user_0?useUnicode=true
        username: root
        password: 123456
      user-1:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://localhost:3308/user_1?useUnicode=true
        username: root
        password: 123456
    props:
      sql-show: true
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

